### ISSUE TITLE
[feature] Rewrite rules for FGD class's studio() attr of .ted files when compiling into mess.fgd

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#14]
I am developing brush prefabs that uses MESS. I find that the classic point entity `size()` bounds inadequate for true visualization of the prefabs positioning in a level as it does not rotate with the entity angles. So I decided to compile a static mdl of the prefabs and reference them in the .ted entity's `studio()` attribute.

File structure:
```
<location of mess>/template_entities/custom/
  ├ my_prefab.map
  ├ my_prefab.ted
  ╰ models/
      ╰ my_prefab.mdl
```
Entity definition in my_prefab.ted (yes, absolute path absolutely works in JACK!):
```fgd
@PointClass 
	studio("<location of mess>/template_entities/custom/models/my_prefab.mdl") 
	= my_prefab : "a very cool prefab"
[]
```

Now, the very clear disadvantage of this is that there is no way to make this work unless the path is absolute, as the end-users could have installed MESS anywhere in their filesystem.

If there is a way to rewrite .ted entity definitions as it's copied to mess.fgd, with the same functions exposed to it as MESS rewrites, this could finally be made portable. Something along the lines of:
```fgd
@PointClass studio("{ted_dir()}/models/my_prefab.mdl") = my_prefab : "a very cool prefab" []
```
...which then resolves to the aforementioned path in mess.fgd.

If this feature can be implemented expeditiously I would be truly grateful. Currently two of my prefab projects (one update, one new) would benefit greatly from this. 🙏‍🙏‍

**Comment by pwitvoet** [comment]
Being able to use give template entities a custom sprite or model is a good idea! I don't know how the various editors resolve relative paths (relative to editor directory, game directory, or .fgd file?) but they wouldn't be reliable anyway because the location of mess.fgd and the template directories are both configurable. So scripting support seems like the way to go here, yes.

The TrenchBroom .fgd variant already uses `{` and `}` for objects and expressions, so the safest approach is to only allow scripts inside strings. That shouldn't take a whole lot of work and it's sufficient for this use-case.

---

Somewhat related to this, I've been thinking about adding a 'package manager' to MESS. This hypothetical tool would show a list of available templates, and upon downloading a template it would also install any related custom content in your game or mod directory. This would make it much easier to share and discover custom entities and scripts, it would also streamline the use of custom content. That could then easily be expanded to also handle editor-only content. But right now it's just an idea.

**Comment by mfaizsyahmi** [comment]
yay
