### ISSUE TITLE
add support to recurse n times

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#2]
New command line switch proposal `-recurse n`

Unlike `-maxrecursion n` that fails if more than n recursion is detected, this switch does what it says on the tin – recurse exactly n times and then stop.

This would be useful for map debugging by allowing mappers to observe the effect of each step of the mess inserts.

**Comment by pwitvoet** [comment]
How about a `-debug` option that changes the behavior of both `-maxrecursion` and `-maxinstance`? If `-debug` is set, then hitting the recursion or instance limit would cause MESS to stop further processing and just save what it has done so far, instead of failing. That would give a little more control over the whole process and there's no chance of accidentally setting a `-maxrecursion` that's lower than the `-recurse` limit.

**Comment by mfaizsyahmi** [comment]
If we're going that way, let's not occupy the very common `-debug` switch and instead use `-onmaxrecursion` and/or `-onmaxinstance` to set the relevant behaviour. Probably have them take the values `fail|stop|continue` to fail the process (current behaviour), stop recursing/resolving (proposed behaviour), or continue to the user's peril :P

**Comment by pwitvoet** [comment]
Instead of a max-recursion setting, which I expect would be quite tedious to work with given how many steps can be involved, I've added a few MScript functions that can help with debugging:
- `assert(condition, message)` - https://pwitvoet.github.io/mess/standard-functions.html#debugging
- `trace(value, message)` - https://pwitvoet.github.io/mess/template-functions.html#debugging

You can use these to log information, or to stop the whole process if a certain condition doesn't hold.
