### ISSUE TITLE
scale as vector

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#3]
Just reposting previous suggestion in TWHL as GitHub issue: https://twhl.info/thread/locate-post/345813

- Make the macro_insert scale property a vector, so you could stretch one axis, and flip another axis.

**Comment by pwitvoet** [comment]
This is a bit tricky, because scaling also adjusts the 'scale' attributes of entities, and those are just a single number.

One possible solution would be to introduce a separate 'geometry_scale' attribute. This would be a vector, and it would only apply to geometry. The existing 'scale' attribute would remain a number, and would apply to entities, and to geometry if the 'geometry_scale' attribute is left empty. This should produce backwards-compatible behavior and allow geometry to be stretched/flipped along different axis. I'll see what I can do.

**Comment by pwitvoet** [comment]
This will be available in v1.2, with the new instance_geometry_scale attribute. I also fixed a bug with negative scales producing invalid brushes.
