### ISSUE TITLE
Make macro_insert entities the standard point entity size

### ISSUE THREAD

**Issue by matthewslouismarie** [pwitvoet/mess#4]
I think it’d be best if macro_insert entities had the standard 16x16x16 size. As of now they take quite some space and stick out of the others, which doesn’t look tidy with complex entity setups.

**Comment by pwitvoet** [comment]
I can see why that's an issue. On the other hand, a macro_insert entity is not quite on the same 'level' as a standard entity because it can pull in a lot of other entities, so I'm inclined to leave it as it is.

You can easily change the size in your own fgd however, by opening mess.fgd and replacing the line:
`@PointClass size(-16 -16 0, 16 16 32) color(255 80 0) base(TemplateInserter, Orientable) = macro_insert : "Insert a template" [ ]`
with:
`@PointClass size(-8 -8 -8, 8 8 8) color(255 80 0) base(TemplateInserter, Orientable) = macro_insert : "Insert a template" [ ]`

**Comment by pwitvoet** [comment]
I've changed the size to 16x16x16 in MESS 1.2.
