### ISSUE TITLE
[feature] add command line switch to disable rewrites

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#8]
I'd like to have a setup where I can verify that MESS is laying out mtl_* entities properly, before proceeding to expand the mtl_* entities. For this I had to repeatedly edit my .ted file to disable and reenable the rewrites which is tedious. 

Having a command line switch to disable entity rewrites would be much helpful. From reading [the docs](https://pwitvoet.github.io/mess/command-line-options.html) such feature doesn't exist yet.

Thanks in advance. 🙏‍

**Comment by pwitvoet** [comment]
That sounds like a good idea.

What you could do for now is to disable the paths under `template-entity-directories:` in your mess.config file, or you could create a second config file with those paths disabled, and use a command-line argument to switch to that config file when needed: `-config no_rewrite.config`.

Alternately, in your case, you could also use a single rewrite block for all of your entities, using the `@MESS REWRITE FOR "my_entity_1" "my_entity_2":` syntax, so there's only one block that needs to be disabled.

**Comment by mfaizsyahmi** [comment]
I figured there would be a way to do it with the config files, but my eyes just glossed over all the settings in it. I'll look at it again. Thanks!

**Comment by pwitvoet** [comment]
The config file approach does have a disadvantage: it'll leave you with an empty `mess.fgd` file until you run MESS again with a normal config file.

I just remembered something else: you can add a `_mess_allow_rewrite_rules` key to your main map's properties. Set the value to `{}` so that no rewrite rule is allowed (this has the same effect as leaving the value empty, but JACK tends to remove custom keys with empty values when you save a map).

**Comment by pwitvoet** [comment]
I've added a `-norewrite` switch that disables rewrite rules.
